### ISSUE TITLE
Update for Solstice Ending

### ISSUE THREAD

**Issue by Miniland1333** [hunternet93/OneShot-Save-Utility#1]
[FTTTTFFFF**T**FFFFFFFFFFFFFFF[i

The bolded "**T**" variable in p-settings.dat controls whether on a new run if it is an original or solstice run.

This only affects when starting a new run, i.e. when there is no save data.

Hope this is a quick fix and will enable people to play whatever run they want!

**Comment by hunternet93** [comment]
Good idea, just added a feature to select between First, Solstice, and Memory runs.
