### ISSUE TITLE
not an issue but

### ISSUE THREAD

**Issue by HellishBro** [hunternet93/OneShot-Save-Utility#11]
how did you figure out the things in settings and stuff? most of it is booleans and random numbers

**Comment by hunternet93** [comment]
It's been a while so I don't remember my exact steps, but it was something along the lines of just changing things and seeing what happened. You might be able to figure out what does what by digging through the [mkxp-oneshot code](https://github.com/elizagamedev/mkxp-oneshot), though it'd be a lot to read through.
