### ISSUE TITLE
This is not an issues, but...

### ISSUE THREAD

**Issue by ArmorOfBerserk** [hunternet93/OneShot-Save-Utility#9]
Forgive me, it was the only way to write to you. We're working on an Italian translation for Oneshot and we needed some saves to test George's dialogues specifically. I'm a programmer and I've seen that to make changes in this tool, you access specific areas of the array. Do you know where the variable responsible for George is located? Better yet, do you know a way to decode the saves?

**Comment by hunternet93** [comment]
Hi ArmorOfBerserk! It's been a few years since I've last touched the code for this, but I was able to get it figured out with a bit of tinkering. The save editor currently only edits the `p-settings.dat` containing stuff that persists between saves, and I don't want to refactor my horrible old code to handle `save.dat` so I made a little script instead.

You'll need Python 3 and the rubymarshal library, available from PyPi / pip.

Please backup your save (using the save utility, or just coping the `save.dat` file somewhere safe) before using this, just in case. I've only tested  it on Linux, so it might require some tinkering on Windows or MacOS. Just set the `desired_george` variable to the George number you want and run, and it should hopefully change the George you see in-game.

```python
desired_george = 6

import os
import platform
from rubymarshal.reader import load as rb_load
from rubymarshal.writer import write as rb_write

if platform.system() == 'Windows':
    dirpath = os.path.join(os.path.expandvars('%appdata%'), 'OneShot')
if platform.system() == 'Linux':
    dirpath = os.path.join(os.path.expanduser('~'), '.local', 'share', 'Oneshot')
if platform.system() == 'Darwin': # MacOS
    dirpath = os.path.join(os.path.expanduser('~'), 'Library', 'Preferences', 'Oneshot')

path = os.path.join(dirpath, 'save.dat')
data = []

with open(path, 'rb') as save:
    for i in range(4):
        data.append(rb_load(save))

    # rubymarshal can only read the first 4 sections
    remaining_data = save.read()

data[3].attributes['@data'][47] = desired_george

with open(path, 'wb') as save:
    for section in data:
        rb_write(save, section)

    save.write(remaining_data)

print(f'Set George to {desired_george}')
```

Let me know if you run into any issues or have any questions or anything! It was fun to relive all the poking at Oneshot's code that I used to do, it's been a while.

**Comment by ArmorOfBerserk** [comment]
Hi and thanks for the script first of all!
I wanted to ask you something: Through save manipulation, is it also possible to create, from existing saves, saves to test various parts of the game? (For example, I start from the Barrens and changing some variables, I arrive at the Glen)
And if so, how?

**Comment by hunternet93** [comment]
You can use the Save Utility to make and load backup saves at various points in the game. This just copies the `save.dat` file to and from a backup location though.

The save file format is complex enough that things like the Niko's location in the game would be tricky to reverse engineer. Using backup saves would be far simpler and would let you jump around to any point in the game you created a save for. However, if you're set on reverse engineering the save file format then looking into the [mkxp-oneshot](https://github.com/elizagamedev/mkxp-oneshot) repo would be a place to start.

**Comment by ArmorOfBerserk** [comment]
Thank you so much! But if I understand correctly, the tool you created
doesn't allow you to create saves from scratch, but to load existing stuff
but quickly, right?

The problem is that we don't know of anywhere that has Oneshot save
files....

Il gio 17 feb 2022, 03:19 Hunter Smith ***@***.***> ha
scritto:

**Comment by hunternet93** [comment]
Yep, the save utility is basically a fancy way of copy/pasting save files to and from a backup folder. It can't edit the saves though, beyond the basics of changing player name, etc.

I'm not sure where to find pre-created save files unfortunately. However, it's not a long game -- you could probably make save files for the whole game in 5-6 hours at most. Once created you can use the save files to jump around in the game as needed, and you can share the created saves with anyone who needs them by just copying the utility's saves folder. The folder is located at:

* Windows: `%APPDATA%\OneShot\OneShot Save Utility Archive`
* MacOS: `~/Library/Preferences/OneShot/OneShot Save Utility Archive`
* Linux `~/.local/share/OneShot/OneShot Save Utility Archive`

**Comment by ArmorOfBerserk** [comment]
So, I've made the saves with the various George's and I thank you so much, thank you so much for your help! <3

**Comment by hunternet93** [comment]
You're welcome, glad I could help! Good luck with the translation project!
